import AssessmentOutlinedIcon from "@mui/icons-material/AssessmentOutlined";
import Inventory2OutlinedIcon from "@mui/icons-material/Inventory2Outlined";
import PendingActionsOutlinedIcon from "@mui/icons-material/PendingActionsOutlined";
import StorefrontOutlinedIcon from "@mui/icons-material/StorefrontOutlined";
import { Box, Card, Chip, Divider, Stack, Typography } from "@mui/material";
import { useCallback, useEffect, useState } from "react";
import { toast } from "react-toastify";
import PageMeta from "../../../components/common/PageMeta";
import { getStockOverview, type StockOverview as StockOverviewData } from "../../../redux/slices/inventoryRedux/stockRedux";

const Metric = ({ icon, label, value, color = "primary.main" }: { icon: React.ReactNode; label: string; value: number; color?: string }) => <Card variant="outlined" sx={{ p: 2.25 }}><Stack direction="row" justifyContent="space-between" spacing={2}><Box><Typography color="text.secondary" variant="body2">{label}</Typography><Typography mt={0.5} variant="h4">{value.toLocaleString("en-LK")}</Typography></Box><Box sx={{ alignItems: "center", bgcolor: "action.hover", borderRadius: 2, color, display: "flex", height: 42, justifyContent: "center", width: 42 }}>{icon}</Box></Stack></Card>;

export default function StockOverview() {
  const [data, setData] = useState<StockOverviewData | null>(null);
  const load = useCallback(async () => { try { setData(await getStockOverview()); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load stock overview."); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <><PageMeta description="Monitor Mobee stock across locations." title="Stock Overview | Mobee Suite" /><Stack spacing={2.5}><Stack direction="row" alignItems="center" spacing={1}><AssessmentOutlinedIcon color="primary" sx={{ fontSize: 24 }} /><Typography variant="h4">Stock Overview</Typography></Stack><Box sx={{ display: "grid", gap: 2, gridTemplateColumns: { xs: "1fr", sm: "repeat(2, 1fr)", xl: "repeat(4, 1fr)" } }}><Metric icon={<Inventory2OutlinedIcon />} label="Total stock units" value={data?.totalUnits ?? 0} /><Metric color="success.main" icon={<StorefrontOutlinedIcon />} label="Available to sell" value={data?.sellableUnits ?? 0} /><Metric color="warning.main" icon={<PendingActionsOutlinedIcon />} label="Approved units waiting" value={data?.pendingStockUnits ?? 0} /><Metric color="text.secondary" icon={<Inventory2OutlinedIcon />} label="Not sellable" value={data?.unavailableUnits ?? 0} /></Box><Box sx={{ display: "grid", gap: 2, gridTemplateColumns: { xs: "1fr", lg: "1fr 1fr" } }}><Card sx={{ minHeight: 300, p: 2.25 }}><Typography fontWeight={700}>Stock by status</Typography><Stack divider={<Divider flexItem />} spacing={0}>{data?.statuses.map((status) => <Stack alignItems="center" direction="row" justifyContent="space-between" key={status.statusId ?? "unknown"} py={1.15}><Chip color={status.isSellable ? "success" : "default"} label={status.statusLabel ?? "Unassigned"} size="small" variant={status.isSellable ? "filled" : "outlined"} /><Typography fontWeight={700}>{status.count.toLocaleString("en-LK")}</Typography></Stack>)}{!data?.statuses.length && <Typography color="text.secondary" py={6} textAlign="center">No stock units have been added yet.</Typography>}</Stack></Card><Card sx={{ minHeight: 300, p: 2.25 }}><Typography fontWeight={700}>Stock by location</Typography><Stack divider={<Divider flexItem />} spacing={0}>{data?.locations.map((location) => <Stack alignItems="center" direction="row" justifyContent="space-between" key={location.locationId ?? "unknown"} py={1.15}><Typography>{location.locationName ?? "No location"}</Typography><Typography fontWeight={700}>{location.count.toLocaleString("en-LK")}</Typography></Stack>)}{!data?.locations.length && <Typography color="text.secondary" py={6} textAlign="center">No stock units have been added yet.</Typography>}</Stack></Card></Box></Stack></>;
}
