import AddRoundedIcon from "@mui/icons-material/AddRounded";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import LocalShippingOutlinedIcon from "@mui/icons-material/LocalShippingOutlined";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import { Autocomplete, Box, Button, Card, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, IconButton, InputAdornment, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import { DataGrid, type GridColDef } from "@mui/x-data-grid";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "react-toastify";
import PageMeta from "../../../components/common/PageMeta";
import useAuth from "../../../hooks/useAuth";
import { createPurchaseOrder, getPurchaseOrder, getPurchaseOrders, getPurchaseOrderStatuses, transitionPurchaseOrder, updatePurchaseOrder, type PurchaseOrder, type PurchaseOrderDetail, type PurchaseOrderItemInput, type PurchaseOrderStatus } from "../../../redux/slices/purchaseRedux/purchaseOrderRedux";
import { getSupplier, getSuppliers, type Supplier, type SupplierProduct } from "../../../redux/slices/purchaseRedux/supplierRedux";
import { getLocations, type Location } from "../../../redux/slices/settingsRedux/businessSettingsRedux";
import { USER_PERMISSIONS } from "../../../utils";
import { fCurrency } from "../../../utils/formatNumber";

type DraftItem = PurchaseOrderItemInput & { productName: string; productSku: string | null };
const pageSizes = [10, 15, 25, 50];
const statusColor = (status: string): "default" | "info" | "warning" | "success" | "error" => ({ draft: "default", pending_approval: "warning", approved: "info", ordered: "success", rejected: "error", cancelled: "error", partially_received: "warning", received: "success" }[status] as "default" | "info" | "warning" | "success" | "error" ?? "default");

export default function PurchaseOrders() {
  const { can } = useAuth(); const [rows, setRows] = useState<PurchaseOrder[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(10); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [supplierFilter, setSupplierFilter] = useState<number | "all">("all"); const [locationFilter, setLocationFilter] = useState<number | "all">("all");
  const [statuses, setStatuses] = useState<PurchaseOrderStatus[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [open, setOpen] = useState(false); const [detail, setDetail] = useState<PurchaseOrderDetail | null>(null); const [tab, setTab] = useState(0); const [supplierId, setSupplierId] = useState(0); const [locationId, setLocationId] = useState(0); const [availableProducts, setAvailableProducts] = useState<SupplierProduct[]>([]); const [items, setItems] = useState<DraftItem[]>([]); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); const [transition, setTransition] = useState<{ action: "submit" | "approve" | "reject" | "order" | "cancel"; buttonLabel: string; resultLabel: string } | null>(null); const [transitionNote, setTransitionNote] = useState("");
  const load = useCallback(async () => { try { const response = await getPurchaseOrders({ locationId: locationFilter, page: page + 1, pageSize, search, status, supplierId: supplierFilter }); setRows(response.items); setTotal(response.pagination.total); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load purchase orders."); } }, [locationFilter, page, pageSize, search, status, supplierFilter]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { Promise.all([getPurchaseOrderStatuses(), getSuppliers({ isActive: "true", page: 1, pageSize: 100, search: "" }), getLocations({ isActive: "true", page: 1, pageSize: 100, search: "", type: "all" })]).then(([statusRows, supplierRows, locationRows]) => { setStatuses(statusRows); setSuppliers(supplierRows.items); setLocations(locationRows.items); }).catch((error) => toast.error(error instanceof Error ? error.message : "Unable to load purchasing setup.")); }, []);
  const loadSupplierProducts = async (id: number) => { setSupplierId(id); setItems([]); if (!id) { setAvailableProducts([]); return; } try { const supplier = await getSupplier(id); setAvailableProducts(supplier.products.filter((product) => product.isActive)); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load supplier products."); } };
  const showCreate = () => { setDetail(null); setSupplierId(0); setLocationId(locations[0]?.id ?? 0); setAvailableProducts([]); setItems([]); setNote(""); setTab(0); setOpen(true); };
  const showDetail = async (row: PurchaseOrder) => { try { const value = await getPurchaseOrder(row.id); setDetail(value); setSupplierId(value.supplierId); setLocationId(value.locationId); setItems(value.items.map((item) => ({ productId: item.productId, productName: item.productName, productSku: item.productSku, quantity: item.quantity, unitPrice: Number(item.unitPrice) }))); const supplier = await getSupplier(value.supplierId); setAvailableProducts(supplier.products.filter((product) => product.isActive)); setNote(""); setTab(0); setOpen(true); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load purchase order."); } };
  const addProduct = (product: SupplierProduct | null) => { if (!product || items.some((item) => item.productId === product.productId)) return; setItems((value) => [...value, { productId: product.productId, productName: product.supplierProductName || product.productName, productSku: product.supplierProductCode || product.productSku, quantity: Math.max(1, product.minimumOrderQty), unitPrice: Number(product.quotedPrice ?? product.lastPurchasingPrice ?? 0) }]); };
  const changeItem = (productId: number, patch: Partial<DraftItem>) => setItems((value) => value.map((item) => item.productId === productId ? { ...item, ...patch } : item));
  const save = async () => { if (!supplierId || !locationId || !items.length) { toast.error("Select a supplier, location, and at least one product."); return; } if (items.some((item) => item.quantity < 1 || item.unitPrice <= 0)) { toast.error("Every product needs a valid quantity and expected price."); return; } setSaving(true); try { const input = { items: items.map(({ productId, quantity, unitPrice }) => ({ productId, quantity, unitPrice })), locationId, note: note.trim() || undefined, supplierId }; const value = detail ? await updatePurchaseOrder(detail.id, input) : await createPurchaseOrder(input); toast.success(`Purchase order ${detail ? "updated" : "created"} successfully.`); setDetail(value); setOpen(false); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save purchase order."); } finally { setSaving(false); } };
  const executeTransition = async () => { if (!detail || !transition) return; setSaving(true); try { const value = await transitionPurchaseOrder(detail.id, transition.action, transitionNote.trim() || undefined); toast.success(`Purchase order ${transition.resultLabel.toLowerCase()} successfully.`); setTransition(null); setTransitionNote(""); setDetail(value); setOpen(false); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update purchase order status."); } finally { setSaving(false); } };
  const actions = detail ? [
    detail.status === "draft" && can(USER_PERMISSIONS.PURCHASE_ORDERS_SUBMIT) ? { action: "submit" as const, buttonLabel: "Submit for Approval", resultLabel: "submitted" } : null,
    detail.status === "pending_approval" && can(USER_PERMISSIONS.PURCHASE_ORDERS_APPROVE) ? { action: "approve" as const, buttonLabel: "Approve", resultLabel: "approved" } : null,
    detail.status === "pending_approval" && can(USER_PERMISSIONS.PURCHASE_ORDERS_APPROVE) ? { action: "reject" as const, buttonLabel: "Reject", resultLabel: "rejected" } : null,
    detail.status === "approved" && can(USER_PERMISSIONS.PURCHASE_ORDERS_ORDER) ? { action: "order" as const, buttonLabel: "Mark Ordered", resultLabel: "marked as ordered" } : null,
    ["draft", "pending_approval", "approved", "ordered"].includes(detail.status) && can(USER_PERMISSIONS.PURCHASE_ORDERS_CANCEL) ? { action: "cancel" as const, buttonLabel: "Cancel Order", resultLabel: "cancelled" } : null,
  ].filter(Boolean) as Array<{ action: "submit" | "approve" | "reject" | "order" | "cancel"; buttonLabel: string; resultLabel: string }> : [];
  const columns = useMemo<GridColDef<PurchaseOrder>[]>(() => [
    { field: "poNumber", headerName: "PO Number", minWidth: 225 }, { field: "supplierName", headerName: "Supplier", flex: 1, minWidth: 200 }, { field: "locationName", headerName: "Location", minWidth: 170 }, { field: "itemCount", headerName: "Items", minWidth: 90, align: "center", headerAlign: "center" }, { field: "totalQuantity", headerName: "Quantity", minWidth: 105, align: "center", headerAlign: "center" }, { field: "totalAmount", headerName: "Total", minWidth: 150, valueFormatter: (value) => fCurrency(Number(value)) }, { field: "statusLabel", headerName: "Status", minWidth: 155, renderCell: ({ row }) => <Chip color={statusColor(row.status)} label={row.statusLabel} size="small" /> }, { field: "timestamp", headerName: "Created", minWidth: 170, valueFormatter: (value) => new Date(Number(value)).toLocaleString("en-LK") },
  ], []);
  const editable = !detail || (detail.status === "draft" && can(USER_PERMISSIONS.PURCHASE_ORDERS_UPDATE));
  const totalAmount = items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
  return <><PageMeta description="Manage Mobee purchase orders." title="Purchase Orders | Mobee Suite" /><Stack spacing={2.5}><Stack alignItems={{ xs: "flex-start", sm: "center" }} direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={1.5}><Stack alignItems="center" direction="row" spacing={1}><LocalShippingOutlinedIcon color="primary" sx={{ fontSize: 23 }} /><Box><Typography variant="h4">Purchase Orders</Typography><Typography color="text.secondary" variant="body2">Create, approve, and order supplier purchases safely.</Typography></Box></Stack>{can(USER_PERMISSIONS.PURCHASE_ORDERS_CREATE) && <Button disabled={!suppliers.length || !locations.length} onClick={showCreate} startIcon={<AddRoundedIcon />} variant="contained">New Purchase Order</Button>}</Stack>
    <Stack alignItems="center" direction="row" flexWrap="wrap" gap={1}><Chip color="info" label={`Visible ${rows.length}`} size="small" variant="outlined" /><Typography color="text.secondary" ml={{ sm: "auto" }} variant="caption">{total} total orders</Typography></Stack>
    <Card sx={{ minHeight: 560, overflow: "hidden" }}><Stack direction={{ xs: "column", md: "row" }} gap={1} p={1.5}><TextField onChange={(e) => { setSearch(e.target.value); setPage(0); }} placeholder="Search PO or supplier" size="small" slotProps={{ input: { startAdornment: <InputAdornment position="start"><SearchRoundedIcon fontSize="small" /></InputAdornment> } }} sx={{ flex: 1, minWidth: 220 }} value={search} /><TextField onChange={(e) => { setStatus(e.target.value); setPage(0); }} select size="small" slotProps={{ select: { native: true } }} value={status}><option value="all">All statuses</option>{statuses.map((value) => <option key={value.id} value={value.name}>{value.label}</option>)}</TextField><TextField onChange={(e) => { setSupplierFilter(e.target.value === "all" ? "all" : Number(e.target.value)); setPage(0); }} select size="small" slotProps={{ select: { native: true } }} value={supplierFilter}><option value="all">All suppliers</option>{suppliers.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</TextField><TextField onChange={(e) => { setLocationFilter(e.target.value === "all" ? "all" : Number(e.target.value)); setPage(0); }} select size="small" slotProps={{ select: { native: true } }} value={locationFilter}><option value="all">All locations</option>{locations.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</TextField></Stack><DataGrid columns={columns} disableRowSelectionOnClick onRowClick={({ row }) => void showDetail(row)} paginationMode="server" paginationModel={{ page, pageSize }} onPaginationModelChange={(model) => { setPage(model.page); setPageSize(model.pageSize); }} pageSizeOptions={pageSizes} rowCount={total} rows={rows} sx={{ border: 0, cursor: "pointer", minHeight: 480 }} /></Card>
  </Stack>
  <Dialog fullScreen fullWidth onClose={() => setOpen(false)} open={open} PaperProps={{ sx: { borderRadius: { md: 3 }, height: { xs: "100%", md: "calc(100% - 48px)" }, m: { md: 3 }, maxWidth: { md: 1500 } } }}><DialogTitle><Stack alignItems="center" direction="row" justifyContent="space-between"><Box><Typography variant="h5">{detail?.poNumber ?? "Create Purchase Order"}</Typography><Typography color="text.secondary" variant="body2">Supplier, location, product variations, quantity, and expected purchase price.</Typography></Box>{detail && <Chip color={statusColor(detail.status)} label={detail.statusLabel} />}</Stack></DialogTitle><Divider />{detail && <Tabs onChange={(_e, value) => setTab(value)} value={tab}><Tab label="Order" /><Tab label={`History (${detail.logs.length})`} /></Tabs>}<DialogContent sx={{ p: { xs: 2, md: 3 } }}>{tab === 1 && detail ? <Stack divider={<Divider flexItem />} spacing={0}>{detail.logs.map((log) => <Stack key={log.id} py={1.5}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={700}>{log.action.split("_").join(" ").replace(/^./, (value: string) => value.toUpperCase())}</Typography><Typography color="text.secondary" variant="caption">{new Date(log.timestamp).toLocaleString("en-LK")}</Typography></Stack><Typography color="text.secondary" variant="body2">By {log.userName}{log.note ? ` • ${log.note}` : ""}</Typography></Stack>)}</Stack> : <Stack spacing={2.5}><Box sx={{ display: "grid", gap: 2, gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" } }}><TextField disabled={!editable} label="Supplier *" onChange={(e) => void loadSupplierProducts(Number(e.target.value))} select slotProps={{ select: { native: true } }} value={supplierId}><option value={0}>Select supplier</option>{suppliers.map((value) => <option key={value.id} value={value.id}>{value.code} — {value.name}</option>)}</TextField><TextField disabled={!editable} label="Location *" onChange={(e) => setLocationId(Number(e.target.value))} select slotProps={{ select: { native: true } }} value={locationId}><option value={0}>Select location</option>{locations.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</TextField></Box>{editable && <Autocomplete getOptionLabel={(option) => `${option.supplierProductName || option.productName}${option.supplierProductCode ? ` — ${option.supplierProductCode}` : ""}`} isOptionEqualToValue={(a, b) => a.id === b.id} onChange={(_e, value) => addProduct(value)} options={availableProducts.filter((product) => !items.some((item) => item.productId === product.productId))} renderInput={(params) => <TextField {...params} label="Add supplier product" placeholder={supplierId ? "Search linked products" : "Select a supplier first"} />} value={null} />}
    <Card variant="outlined" sx={{ overflowX: "auto" }}><Box sx={{ minWidth: 900 }}><Box sx={{ bgcolor: "action.hover", display: "grid", gridTemplateColumns: "2fr .8fr 1fr 1fr 56px", px: 2, py: 1.5 }}>{["Product", "Quantity", "Expected Price", "Line Total", ""].map((label, index) => <Typography fontSize={12.5} fontWeight={700} key={`${label}-${index}`}>{label}</Typography>)}</Box>{items.map((item) => <Box key={item.productId} sx={{ alignItems: "center", borderTop: 1, borderColor: "divider", display: "grid", gap: 1.5, gridTemplateColumns: "2fr .8fr 1fr 1fr 56px", minHeight: 70, px: 2, py: 1 }}><Box><Typography fontSize={13.5} fontWeight={700}>{item.productName}</Typography><Typography color="text.secondary" variant="caption">{item.productSku || `Product #${item.productId}`}</Typography></Box><TextField disabled={!editable} inputProps={{ min: 1 }} onChange={(e) => changeItem(item.productId, { quantity: Math.max(1, Number(e.target.value)) })} size="small" type="number" value={item.quantity} /><TextField disabled={!editable} inputProps={{ min: 0.01, step: 0.01 }} onChange={(e) => changeItem(item.productId, { unitPrice: Number(e.target.value) })} size="small" type="number" value={item.unitPrice} /><Typography fontSize={13.5} fontWeight={700}>{fCurrency(item.quantity * item.unitPrice)}</Typography><IconButton disabled={!editable} onClick={() => setItems((value) => value.filter(({ productId }) => productId !== item.productId))} color="error" size="small"><DeleteOutlineRoundedIcon fontSize="small" /></IconButton></Box>)}{!items.length && <Typography color="text.secondary" py={7} textAlign="center">Select a supplier and add products to this order.</Typography>}<Divider /><Stack alignItems="center" direction="row" justifyContent="flex-end" p={2} spacing={2}><Typography color="text.secondary">Order Total</Typography><Typography variant="h6">{fCurrency(totalAmount)}</Typography></Stack></Box></Card><TextField disabled={!editable} label="Internal Note" minRows={3} multiline onChange={(e) => setNote(e.target.value)} value={note} /></Stack>}</DialogContent><DialogActions sx={{ borderTop: 1, borderColor: "divider", flexWrap: "wrap", p: 2 }}><Button color="inherit" onClick={() => setOpen(false)}>Close</Button>{detail && actions.map((value) => <Button color={["reject", "cancel"].includes(value.action) ? "error" : "primary"} key={value.action} onClick={() => setTransition(value)} variant={value.action === "submit" || value.action === "approve" || value.action === "order" ? "contained" : "outlined"}>{value.buttonLabel}</Button>)}{editable && <Button disabled={saving || !items.length} onClick={() => void save()} variant="contained">{detail ? "Save Draft" : "Create Draft"}</Button>}</DialogActions></Dialog>
  <Dialog fullWidth maxWidth="xs" onClose={() => setTransition(null)} open={Boolean(transition)}><DialogTitle>{transition?.buttonLabel}?</DialogTitle><DialogContent><Stack spacing={2} pt={1}><Typography color="text.secondary">The backend will verify the current status, supplier, location, products, prices, and your permission before applying this action.</Typography><TextField label="Note (optional)" minRows={3} multiline onChange={(e) => setTransitionNote(e.target.value)} value={transitionNote} /></Stack></DialogContent><DialogActions><Button color="inherit" onClick={() => setTransition(null)}>Cancel</Button><Button color={transition && ["reject", "cancel"].includes(transition.action) ? "error" : "primary"} disabled={saving} onClick={() => void executeTransition()} variant="contained">Confirm</Button></DialogActions></Dialog></>;
}
