import AddRoundedIcon from "@mui/icons-material/AddRounded";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import FormatListNumberedRoundedIcon from "@mui/icons-material/FormatListNumberedRounded";
import { Box, Button, Card, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Stack, TextField, Typography } from "@mui/material";
import { DataGrid, type GridColDef } from "@mui/x-data-grid";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "react-toastify";
import PageMeta from "../../../components/common/PageMeta";
import useAuth from "../../../hooks/useAuth";
import { createDocumentSequence, getDocumentSequences, getLocations, updateDocumentSequence, type DocumentSequence, type DocumentSequenceInput, type Location } from "../../../redux/slices/settingsRedux/businessSettingsRedux";
import { USER_PERMISSIONS } from "../../../utils";

const types = ["PURCHASE_ORDER", "GOODS_RECEIVED_NOTE", "PURCHASE_RETURN", "SUPPLIER_INVOICE", "SUPPLIER_PAYMENT", "STOCK_BARCODE", "SUPPLIER_CODE"];
const labels: Record<string, string> = { PURCHASE_ORDER: "Purchase Order", GOODS_RECEIVED_NOTE: "Goods Received Note", PURCHASE_RETURN: "Purchase Return", SUPPLIER_INVOICE: "Supplier Invoice", SUPPLIER_PAYMENT: "Supplier Payment", STOCK_BARCODE: "Stock Barcode", SUPPLIER_CODE: "Supplier Code" };
const year = new Date().getFullYear();
const empty: DocumentSequenceInput = { documentType: "PURCHASE_ORDER", locationId: 0, prefix: "PO", startingNumber: 0, year };
export default function DocumentSequences() {
  const { can } = useAuth(); const [rows, setRows] = useState<DocumentSequence[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [type, setType] = useState("all"); const [locationId, setLocationId] = useState<number | "all">("all"); const [sequenceYear, setSequenceYear] = useState<number | "all">("all"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<DocumentSequence | null>(null); const [form, setForm] = useState<DocumentSequenceInput>(empty); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { setRows(await getDocumentSequences({ documentType: type, locationId, year: sequenceYear })); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load document sequences."); } }, [locationId, sequenceYear, type]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { void getLocations({ isActive: "true", page: 1, pageSize: 100, search: "", type: "all" }).then((value) => setLocations(value.items)).catch((error) => toast.error(error instanceof Error ? error.message : "Unable to load locations.")); }, []);
  const showCreate = () => { setEditing(null); setForm({ ...empty, locationId: locations[0]?.id ?? 0 }); setOpen(true); };
  const showEdit = (row: DocumentSequence) => { setEditing(row); setForm({ documentType: row.documentType, locationId: row.locationId, prefix: row.prefix, startingNumber: row.lastNumber, year: row.year }); setOpen(true); };
  const save = async () => { if (!form.prefix.trim() || !form.locationId) { toast.error("Location and prefix are required."); return; } setSaving(true); try { if (editing) await updateDocumentSequence(editing.id, form.prefix); else await createDocumentSequence(form); toast.success(`Document sequence ${editing ? "updated" : "created"}.`); setOpen(false); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save document sequence."); } finally { setSaving(false); } };
  const columns = useMemo<GridColDef<DocumentSequence>[]>(() => [
    { field: "documentType", headerName: "Document", flex: 1, minWidth: 200, valueFormatter: (value) => labels[value] ?? value }, { field: "locationName", headerName: "Location", minWidth: 190, valueFormatter: (value) => value || "—" }, { field: "year", headerName: "Year", minWidth: 100 }, { field: "prefix", headerName: "Prefix", minWidth: 120, renderCell: ({ value }) => <Chip color="primary" label={value} size="small" variant="outlined" /> }, { field: "lastNumber", headerName: "Last Issued Number", minWidth: 175, valueFormatter: (value) => Number(value).toLocaleString() }, { field: "preview", headerName: "Next Number Preview", flex: 1, minWidth: 230, valueGetter: (_value, row) => `${row.prefix}-${String(row.locationId).padStart(3, "0")}-${row.year}-${String(Number(row.lastNumber) + 1).padStart(6, "0")}` },
    { field: "actions", headerName: "Actions", align: "center", headerAlign: "center", minWidth: 90, sortable: false, filterable: false, renderCell: ({ row }) => <Button disabled={!can(USER_PERMISSIONS.DOCUMENT_SEQUENCES_UPDATE)} onClick={() => showEdit(row)} size="small" startIcon={<EditOutlinedIcon sx={{ fontSize: 18 }} />}>Edit</Button> },
  ], [can]);
  return <><PageMeta description="Configure Mobee document numbering." title="Document Sequences | Mobee Suite" /><Stack spacing={2.5}><Stack alignItems={{ xs: "flex-start", sm: "center" }} direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={1.5}><Stack alignItems="center" direction="row" spacing={1}><FormatListNumberedRoundedIcon color="primary" sx={{ fontSize: 23 }} /><Typography variant="h4">Document Sequences</Typography></Stack>{can(USER_PERMISSIONS.DOCUMENT_SEQUENCES_CREATE) && <Button disabled={!locations.length} onClick={showCreate} startIcon={<AddRoundedIcon />} variant="contained">New Sequence</Button>}</Stack>
    <Card sx={{ minHeight: 520, overflow: "hidden" }}><Stack direction={{ xs: "column", sm: "row" }} gap={1} p={1.5}><TextField fullWidth onChange={(e) => setType(e.target.value)} select size="small" slotProps={{ select: { native: true } }} value={type}><option value="all">All documents</option>{types.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</TextField><TextField fullWidth onChange={(e) => setLocationId(e.target.value === "all" ? "all" : Number(e.target.value))} select size="small" slotProps={{ select: { native: true } }} value={locationId}><option value="all">All locations</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</TextField><TextField fullWidth onChange={(e) => setSequenceYear(e.target.value === "all" ? "all" : Number(e.target.value))} select size="small" slotProps={{ select: { native: true } }} value={sequenceYear}><option value="all">All years</option>{[year - 1, year, year + 1].map((value) => <option key={value} value={value}>{value}</option>)}</TextField></Stack><DataGrid columns={columns} disableRowSelectionOnClick pageSizeOptions={[10, 15, 25, 50]} initialState={{ pagination: { paginationModel: { pageSize: 10 } } }} rows={rows} sx={{ border: 0, minHeight: 440 }} /></Card>
  </Stack><Dialog fullWidth maxWidth="sm" onClose={() => setOpen(false)} open={open}><DialogTitle>{editing ? "Edit Document Sequence" : "Create Document Sequence"}</DialogTitle><DialogContent><Stack spacing={2} pt={1}><TextField disabled={Boolean(editing)} label="Document Type" onChange={(e) => setForm((v) => ({ ...v, documentType: e.target.value }))} select slotProps={{ select: { native: true } }} value={form.documentType}>{types.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</TextField><TextField disabled={Boolean(editing)} label="Location" onChange={(e) => setForm((v) => ({ ...v, locationId: Number(e.target.value) }))} select slotProps={{ select: { native: true } }} value={form.locationId}>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</TextField><Box sx={{ display: "grid", gap: 2, gridTemplateColumns: "1fr 1fr" }}><TextField label="Prefix *" onChange={(e) => setForm((v) => ({ ...v, prefix: e.target.value.toUpperCase() }))} value={form.prefix} /><TextField disabled={Boolean(editing)} inputProps={{ min: 2000, max: 9999 }} label="Year" onChange={(e) => setForm((v) => ({ ...v, year: Number(e.target.value) }))} type="text" value={form.year} /></Box><TextField disabled={Boolean(editing)} helperText={editing ? "Issued counters are protected and cannot be changed." : "The next generated number will be this value plus one."} inputProps={{ min: 0 }} label="Starting Number" onChange={(e) => setForm((v) => ({ ...v, startingNumber: Number(e.target.value) }))} type="text" value={form.startingNumber} /></Stack></DialogContent><DialogActions><Button color="inherit" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={saving} onClick={() => void save()} variant="contained">Save Sequence</Button></DialogActions></Dialog></>;
}
