import AddRoundedIcon from "@mui/icons-material/AddRounded";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import LocationOnOutlinedIcon from "@mui/icons-material/LocationOnOutlined";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import { Box, Button, Card, Chip, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, InputAdornment, Stack, Switch, TextField, Tooltip, Typography } from "@mui/material";
import { DataGrid, type GridColDef } from "@mui/x-data-grid";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "react-toastify";
import PageMeta from "../../../components/common/PageMeta";
import useAuth from "../../../hooks/useAuth";
import { createLocation, getLocations, updateLocation, updateLocationStatus, type Location, type LocationInput } from "../../../redux/slices/settingsRedux/businessSettingsRedux";
import { USER_PERMISSIONS } from "../../../utils";

const empty: LocationInput = { address: null, code: "", isActive: true, name: "", phone: null, type: "shop" };
const pageSizes = [10, 15, 25, 50];
export default function Locations() {
  const { can } = useAuth();
  const [rows, setRows] = useState<Location[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(10);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [form, setForm] = useState<LocationInput>(empty); const [editing, setEditing] = useState<Location | null>(null); const [open, setOpen] = useState(false); const [statusTarget, setStatusTarget] = useState<Location | null>(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const response = await getLocations({ isActive: status, page: page + 1, pageSize, search, type: "all" }); setRows(response.items); setTotal(response.pagination.total); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load locations."); } }, [page, pageSize, search, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  const showForm = (location?: Location) => { setEditing(location ?? null); setForm(location ? { address: location.address, code: location.code, isActive: location.isActive, name: location.name, phone: location.phone, type: location.type } : empty); setOpen(true); };
  const save = async () => { if (!form.name.trim() || !form.code.trim()) { toast.error("Location name and code are required."); return; } setSaving(true); try { if (editing) { await updateLocation(editing.id, { address: form.address, code: form.code, name: form.name, phone: form.phone, type: form.type }); } else await createLocation(form); toast.success(`Location ${editing ? "updated" : "created"} successfully.`); setOpen(false); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save location."); } finally { setSaving(false); } };
  const confirmStatus = async () => { if (!statusTarget) return; try { await updateLocationStatus(statusTarget.id, !statusTarget.isActive); toast.success(`Location ${statusTarget.isActive ? "deactivated" : "activated"}.`); setStatusTarget(null); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update location status."); } };
  const columns = useMemo<GridColDef<Location>[]>(() => [
    { field: "code", headerName: "Code", minWidth: 145 }, { field: "name", headerName: "Location", flex: 1, minWidth: 190 },
    { field: "type", headerName: "Type", minWidth: 150, valueFormatter: (value) => value === "repairCentre" ? "Repair Centre" : String(value).replace(/^./, (v) => v.toUpperCase()) },
    { field: "phone", headerName: "Phone", minWidth: 150, valueFormatter: (value) => value || "—" }, { field: "address", headerName: "Address", flex: 1, minWidth: 230, valueFormatter: (value) => value || "—" },
    { field: "isActive", headerName: "Status", minWidth: 105, renderCell: ({ value }) => <Chip color={value ? "success" : "default"} label={value ? "Active" : "Inactive"} size="small" /> },
    { field: "actions", headerName: "Actions", align: "center", headerAlign: "center", minWidth: 120, sortable: false, filterable: false, renderCell: ({ row }) => <Stack alignItems="center" direction="row" height="100%" justifyContent="center"><Tooltip title="Edit location"><span><IconButton disabled={!can(USER_PERMISSIONS.LOCATIONS_UPDATE)} onClick={() => showForm(row)} size="small"><EditOutlinedIcon sx={{ fontSize: 18 }} /></IconButton></span></Tooltip><Tooltip title={row.isActive ? "Deactivate" : "Activate"}><span><Switch checked={row.isActive} disabled={!can(USER_PERMISSIONS.LOCATIONS_UPDATE)} onChange={() => setStatusTarget(row)} size="small" /></span></Tooltip></Stack> },
  ], [can]);
  return <><PageMeta description="Manage Mobee business locations." title="Locations | Mobee Suite" /><Stack spacing={2.5}>
    <Stack alignItems={{ xs: "flex-start", sm: "center" }} direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={1.5}><Stack alignItems="center" direction="row" spacing={1}><LocationOnOutlinedIcon color="primary" sx={{ fontSize: 23 }} /><Typography variant="h4">Locations</Typography></Stack>{can(USER_PERMISSIONS.LOCATIONS_CREATE) && <Button onClick={() => showForm()} startIcon={<AddRoundedIcon />} variant="contained">New Location</Button>}</Stack>
    <Stack alignItems="center" direction="row" flexWrap="wrap" gap={1}><Chip color="info" label={`Visible ${rows.length}`} size="small" variant="outlined" /><Chip color="success" label={`Active ${rows.filter((row) => row.isActive).length}`} size="small" variant="outlined" /><Typography color="text.secondary" ml={{ sm: "auto" }} variant="caption">{total} total locations</Typography></Stack>
    <Card sx={{ minHeight: 520, overflow: "hidden" }}><Stack direction={{ xs: "column", sm: "row" }} gap={1} justifyContent="flex-end" p={1.5}><TextField onChange={(e) => { setSearch(e.target.value); setPage(0); }} placeholder="Search locations" size="small" slotProps={{ input: { startAdornment: <InputAdornment position="start"><SearchRoundedIcon fontSize="small" /></InputAdornment> } }} sx={{ width: { xs: "100%", sm: 280 } }} value={search} /><TextField onChange={(e) => { setStatus(e.target.value); setPage(0); }} select size="small" slotProps={{ select: { native: true } }} value={status}><option value="all">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></TextField></Stack><DataGrid columns={columns} disableRowSelectionOnClick paginationMode="server" paginationModel={{ page, pageSize }} onPaginationModelChange={(model) => { setPage(model.page); setPageSize(model.pageSize); }} pageSizeOptions={pageSizes} rowCount={total} rows={rows} sx={{ border: 0, minHeight: 440 }} /></Card>
  </Stack>
  <Dialog fullWidth maxWidth="sm" onClose={() => setOpen(false)} open={open}><DialogTitle>{editing ? "Edit Location" : "Create Location"}</DialogTitle><DialogContent><Box sx={{ display: "grid", gap: 2, gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr" }, pt: 1 }}><TextField label="Location Name *" onChange={(e) => setForm((v) => ({ ...v, name: e.target.value }))} value={form.name} /><TextField disabled={Boolean(editing)} label="Location Code *" onChange={(e) => setForm((v) => ({ ...v, code: e.target.value.toUpperCase() }))} value={form.code} /><TextField label="Location Type *" onChange={(e) => setForm((v) => ({ ...v, type: e.target.value as LocationInput["type"] }))} select slotProps={{ select: { native: true } }} value={form.type}><option value="shop">Shop</option><option value="warehouse">Warehouse</option><option value="repairCentre">Repair Centre</option></TextField><TextField label="Phone" onChange={(e) => setForm((v) => ({ ...v, phone: e.target.value || null }))} value={form.phone ?? ""} /><TextField label="Address" minRows={3} multiline onChange={(e) => setForm((v) => ({ ...v, address: e.target.value || null }))} sx={{ gridColumn: { sm: "1/-1" } }} value={form.address ?? ""} /></Box></DialogContent><DialogActions><Button color="inherit" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={saving} onClick={() => void save()} variant="contained">{editing ? "Save Changes" : "Create Location"}</Button></DialogActions></Dialog>
  <Dialog fullWidth maxWidth="xs" onClose={() => setStatusTarget(null)} open={Boolean(statusTarget)}><DialogTitle>{statusTarget?.isActive ? "Deactivate location?" : "Activate location?"}</DialogTitle><DialogContent><Typography color="text.secondary">{statusTarget?.isActive ? "The backend will block this operation if the location has active purchase orders." : "This location will become available for new purchasing activity."}</Typography></DialogContent><DialogActions><Button color="inherit" onClick={() => setStatusTarget(null)}>Cancel</Button><Button color={statusTarget?.isActive ? "error" : "primary"} onClick={() => void confirmStatus()} variant="contained">Confirm</Button></DialogActions></Dialog></>;
}
